### ISSUE TITLE
Large datasets times scaling exponential

### ISSUE THREAD

**Issue by spech66** [RobinCK/typeorm-fixtures#109]
I tried to create several datasets for testing our application.
Starting with 100 base objects * 4 sub objects + a few thousand additional entities. Takes ~1 min
1000 * 4 + x thousand. Takes ~4min
10000 * 4 + x thousand. Crashes after 4+ hours.

Debug output
```
Connection to database...
Database is connected
Loading fixtureConfigs
Resolving fixtureConfigs
```

Node Profiling of first 5minutes.
![image](https://user-images.githubusercontent.com/22615238/75957728-e9f07780-5eba-11ea-998d-7d7e6738a46c.png)
Looks like most time is spend in the resolver at `resolveDeepDependencies(item) {`

**Comment by RobinCK** [comment]
Welcome to PR
