### ISSUE TITLE
Setting up a Seed to generate replicable fixtures

### ISSUE THREAD

**Issue by Sturgelose** [RobinCK/typeorm-fixtures#12]
I've been trying to check the possibility to set the generation seed for the fixtures, so they can be reproducible in tests, however I haven't seen the `faker.seed()` call anywhere in the code.

Is there any possibility to add some sort of configuration to the project so tests can be reproducible?
This way, fixtures can be loaded before tests and tests can be reproducible.

Otherwise, each time fixtures are run, the values in the database get updated

**Comment by RobinCK** [comment]
Sorry but I do not understand the question.

**Comment by Sturgelose** [comment]
When you generate fixtures randomly, if you want to use them for testing, the results may change and they are not reproducible. Thus, faker.js exposes the option to set the pseudrandomness seed, which is the way to replicate the generation of random data (in this case the fixtures), so you can reproduce again the same data you generate in a certain moment.

So the question was if there is any way to configure the faker.js used under the hood by this library in order to set the seed value (faker.js accepts this option according to its docs)

**Comment by jeanfortheweb** [comment]
You could load the fixtures programmatically and set the faker seed there, right?
