### ISSUE TITLE
[Feature request] Change faker.js Locale

### ISSUE THREAD

**Issue by vicentenoriega** [RobinCK/typeorm-fixtures#146]
Hi everyone,

First of all, thanks for this awesome library, it's so useful!

I would like that typeorm-fixtures provide some way to change the [Fakerjs locale](https://github.com/marak/Faker.js/#localization). That's all.

Thanks in advance.

**Comment by tomasz-szymanek** [comment]
👍 👍 👍 
I really need this!

**Comment by RobinCK** [comment]
@tomasz-szymanek thanks, 1.8.0 release
