### ISSUE TITLE
[Question] Is it possible to use specific field of the related object?

### ISSUE THREAD

**Issue by dtolstyi** [RobinCK/typeorm-fixtures#154]
Hi,

There are many examples where related object is fully inserted into the parent object but, sometimes, you need just one field from the related object (e.g. `id`). Is it possible to do something like: 
```
profileId: `@profile5.id`
```
I know I can do it using processors but it looks a bit ugly, imo.

Thank you.

**Comment by RobinCK** [comment]
This is not possible at the moment

**Comment by paulorsbrito** [comment]
As of 4.1.0, this is still not possible?
