### ISSUE TITLE
[Feature request] Please hardcode faker package to 5.5.3

### ISSUE THREAD

**Issue by cadavre** [RobinCK/typeorm-fixtures#178]
Due to recent events, connected with `faker` library author, I propose to hardcode faker library as version `5.5.3` probably would be the last one ever released. There is fake `6.6.6` version that should be never used.

References:

https://github.com/RobinCK/typeorm-fixtures/blob/master/package.json#L86

https://www.npmjs.com/package/faker

> TLDR: the author had a tragedy in his life that left him nearly broke and decided that he didn't want to do free work to support Fortune 500s. Deleted the repo.

**Comment by RobinCK** [comment]
Do you suggest to hardcode 
```
"faker": "5.5.3"
```
in package.json?

**Comment by cadavre** [comment]
Yes, indeed.

**Comment by RobinCK** [comment]
thanks @cadavre 
done.
1.10.1 version released
