### ISSUE TITLE
[Feature request] Add support for typeorm ^0.3.0

### ISSUE THREAD

**Issue by glen-84** [RobinCK/typeorm-fixtures#189]
Please add support for typeorm 0.3.0.

**Comment by imnotjames** [comment]
TypeORM 0.3.0 isn't exactly backwards compatible, wouldn't that cause breakage?

**Comment by glen-84** [comment]
@imnotjames True, I've updated the title and description to reflect the actual request.

**Comment by maximelafarie** [comment]
@glen-84 since there's no answer since you created this issue, have you come up with another solution that supports typeorm 0.3.x ?

**Comment by glen-84** [comment]
@maximelafarie I haven't.

**Comment by ovitaliw** [comment]
I created another ormconfig file with the typeorm v 0.2 specs and I use this file to run the typeorm-fixtures

**Comment by kevin-lot** [comment]
I did that: https://github.com/RobinCK/typeorm-fixtures/pull/194
Some reviews are welcome.

**Comment by RobinCK** [comment]
typeorm-fixtures-cli@2.0.0

**Comment by christopheblin** [comment]
@RobinCK let's say that I have a file named orm-config.ts in my source code

```
const options: PostgresConnectionOptions = {
  type: 'postgres',
  url: 'xxx',
  synchronize: false,
  entities: [...],
  migrations: [...],
});

export default options;
```

At the moment, to use typeorm migrations, I am required to create a orm-datasource.ts with something like

```
import { DataSource } from 'typeorm';
import DATASOURCE_OPTIONS from './ormconfig';

export const DATASOURCE = new DataSource(DATASOURCE_OPTIONS);
```

Would it be possible somehow to work like the migrations and to use the datasource directly (instead of creating the datasource form the options) ?

**Comment by kevin-lot** [comment]
@christopheblin Otherwise said, we should have consistent CLI with the typeorm in order to only have a single file orm-datasource.ts

That's the goal, did you try it ?

**Comment by christopheblin** [comment]
@kevin-lot yes I did try it before posting my comment :)

```
fixtures ./test/fixtures/typeorm --sync --require=ts-node/register --require=tsconfig-paths/register --dataSource ./src/database/ormconfig.ts
Progress  [██████████████████████████████████████████████████] 100% | ETA: 0s | 29/29 

$ fixtures ./test/fixtures/typeorm --sync --require=ts-node/register --require=tsconfig-paths/register --dataSource ./src/database/ormdatasource.ts
Fail fixture loading: Wrong driver: "undefined" given. Supported drivers are: "aurora-mysql", "aurora-postgres", "better-sqlite3", "capacitor", "cockroachdb", "cordova", "expo", "mariadb", "mongodb", "mssql", "mysql", "nativescript", "oracle", "postgres", "react-native", "sap", "sqlite", "sqljs", "spanner".
MissingDriverError: Wrong driver: "undefined" given. Supported drivers are: "aurora-mysql", "aurora-postgres", "better-sqlite3", "capacitor", "cockroachdb", "cordova", "expo", "mariadb", "mongodb", "mssql", "mysql", "nativescript", "oracle", "postgres", "react-native", "sap", "sqlite", "sqljs", "spanner".
    ...
    at typeorm-fixtures-cli/src/util/createConnection.ts:9:12
```

I think that https://github.com/RobinCK/typeorm-fixtures/pull/194/files#diff-eeaaf2a463a7b8738e67bea0c114825c52af230e7d11b59e431dcfe226d48540 is responsible for that

```
export async function createConnection(
    config: { root?: string | undefined; configName?: string | undefined },
    connectionName: string,
): Promise<DataSource> {
    const options: DataSourceOptions = await new ConnectionOptionsReader(config).get(connectionName);

    return new DataSource(options).initialize();
}
```

Or maybe something else, if you have any idea ?

**Comment by kevin-lot** [comment]
@christopheblin I had this issue.

What's your url look like ?
```
url: postgres://login:pwd@localhost:5432/my_database
```
Or your url starts by `postgresql` ?

**Comment by christopheblin** [comment]
@kevin-lot I did that modification directly in the node_modules

```
function createConnection(config, connectionName) {
    return __awaiter(this, void 0, void 0, function* () {
        console.log(config, connectionName)
        const options = yield new typeorm_1.ConnectionOptionsReader(config).get(connectionName);
        console.log(options)
        return new typeorm_1.DataSource(options).initialize();
    });
}
```

Which outputs
```
{
  root: '/Users/christopheblin/sources/excalibur/apps/graal/ticket/src/database',
  configName: 'ormdatasource'
} default
{
  DATASOURCE: <ref *1> DataSource {
    '@instanceof': Symbol(DataSource),
    migrations: [],
    subscribers: [],
    entityMetadatas: [],
    name: 'default',
    options: {
      type: 'postgres',
      url: 'postgres://root:root@db:5432/test',
      synchronize: false,
      entities: [Array],
      migrations: [Array]
    }
    ...
   Fail fixture loading: Wrong driver: "undefined" given ...
```

It works if I change by a ugly 
```
return "DATASOURCE" in options ? options.DATASOURCE.initialize() : new typeorm_1.DataSource(options).initialize();
```

-> I htink there really is something wrong in createConnection because it tries to `new Datasource` on something that already contains a DataSource

**Comment by kevin-lot** [comment]
@christopheblin

I read your connection configuration, you have an issue in it.
You put your configuration in the datasource.
Datasource has to build the configuration directly.

**Comment by christopheblin** [comment]
@kevin-lot I'll try to create a repo with the issue and I will create a new issue

**Comment by christopheblin** [comment]
@kevin-lot for info, I need to export both the options AND the datasource in order to use the datasource with migrations/fixtures and the options with nestjs/typeorm

**Comment by kevin-lot** [comment]
@christopheblin I'm currently running fixtures and migrations with only one datasource (and no options).

**Comment by christopheblin** [comment]
@kevin-lot OK, I finally found it

I need noth DATASROUCE_OPTIONS and DATASOURCE because I am using migrations, fixtures and nestjs

In nestjs, I need to provide only the DATASOURCE_OPTIONS whereas in migrations and fixtures I need to provide DATASOURCE

-> so indeed the problem is not really in fixtures :+1:
