### ISSUE TITLE
Update joi dependency to @hapi/joi

### ISSUE THREAD

**Issue by OJezu** [RobinCK/typeorm-fixtures#24]
During installation of typeorm-fixtures-cli following warning is generated:

`warning typeorm-fixtures-cli > joi@14.3.1: This module has moved and is now available at @hapi/joi. Please update your dependencies as this version is no longer maintained an may contain bugs and security issues.
`

**Comment by pm-nsimic** [comment]
any movement on this one?

**Comment by johannesschobel** [comment]
I have just created a PR to address this issue! Hopefully, @RobinCK can take a look at it!
All the best

**Comment by RobinCK** [comment]
@johannesschobel thanks!
merged and released 1.4 version
