### ISSUE TITLE
Add config loading from ormconfig.ts in root directory

### ISSUE THREAD

**Issue by Insidexa** [RobinCK/typeorm-fixtures#5]
we use `ormconfig.ts` because it is most flexible for configuration `TypeOrm`
`npx fixtures -c ormconfig.ts database/fixtures`
output
```
Fail fixture loading: Unexpected token {
(node:32337) UnhandledPromiseRejectionWarning: ConnectionNotFoundError: Connection "default" was not found.
```

**Comment by RobinCK** [comment]
please show configuration example

**Comment by Insidexa** [comment]
```
import { SnakeNamingStrategy } from '../modules/common/typeorm/snake-case-naming.strategy';

const {
    DB_TYPE,
    DB_HOST,
    DB_PORT,
    DB_NAME,
    DB_PASSWORD,
    DB_USERNAME,
    DB_MIGRATIONS,
    DB_MIGRATIONS_DIR,
    DB_ENTITIES,
} = process.env;

module.exports = {
    type: DB_TYPE,
    host: DB_HOST,
    port: DB_PORT,
    database: DB_NAME,
    username: DB_USERNAME,
    password: DB_PASSWORD,
    entities: [DB_ENTITIES],
    migrations: [DB_MIGRATIONS],
    cli: {
        migrationsDir: DB_MIGRATIONS_DIR,
    },
    namingStrategy: new SnakeNamingStrategy(),
}
```

**Comment by RobinCK** [comment]
Everything works if you 
 - add the `name` property, for example `default`
 - then build the project
 - and in cli specify the path to js file

tested on [sample project](https://github.com/RobinCK/typeorm-fixtures-sample)
config:

```typescript
module.exports = {
    name: 'default',
    type: 'postgres',
    host: 'localhost',
    database: 'test',
    username: 'root',
    password: 'root',
    entities: ['./dist/entity/**/*.js'],
    cli: {
        entitiesDir: 'entity',
    },
};
```

run command:

```bash
npx fixtures ./fixtures --config dist/ormconfig.js --sync
```

**Comment by Insidexa** [comment]
but need in dev mode without build project, typeorm in dev mode loaded ts config
maybe you need see source code how typeorm load ormconfig.ts and apply to your project :)

**Comment by RobinCK** [comment]
please check next solution
1. install `ts-node` for dev environment
2. update this package to `0.4.0` 
3. ```npx fixtures ./fixtures --config ./ormconfig.ts --sync --require ts-node/register```

**Comment by Insidexa** [comment]
Thank you, its worked ! )
