### ISSUE TITLE
Many to many always seems to be failing

### ISSUE THREAD

**Issue by Joebob12** [RobinCK/typeorm-fixtures#58]
I have a manyToMany relationship in one of my entities and if I comment it out it works fine: something like the following:

```
@ManyToMany(type => Subject, subject => subject.tutors)
@JoinTable()
subjects: Subject[]
```

after trying to run the fixture I get:
```
Fail fixture loading: Maximum call stack size exceeded
RangeError: Maximum call stack size exceeded
```

Has anyone tried getting fixtures to work with ManyToMany relationships?

**Comment by RobinCK** [comment]
я думаю это не тестировалось

**Comment by RobinCK** [comment]
Sorry. I think it was not tested

**Comment by RobinCK** [comment]
I think you need to add reference only on one side and then everything will work

**Comment by Joebob12** [comment]
Thank you that was actually the issue and now it works great! Sorry for my
mixup. =)
